spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hidden-method:
      filter:
        enabled: true
gcp:
  storage:
      bucket: bucket-booking
      credentials:
        location: file:/D/deep-ethos-435317-v2-2cb8308d2257.json
